# Generated by Django 4.2.3 on 2023-07-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requeriments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Descrição do curso'),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('ba', 'Básico'), ('in', 'Intermediário'), ('av', 'Avançado')], max_length=2, verbose_name='Nivel'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(verbose_name='Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='jobs.skill', verbose_name='Skills necessárias'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título do curso'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(related_name='jobs', to='jobs.requeriments', verbose_name='Pré-requisito do curso'),
        ),
    ]
