# Generated by Django 4.2.3 on 2023-07-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_requeriments_alter_job_description_alter_job_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.DeleteModel(
            name='Requeriments',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default=1, verbose_name='Pré-requisito do curso'),
            preserve_default=False,
        ),
    ]
