# Generated by Django 5.2.8 on 2026-01-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username tentado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('blocked', 'Bloqueado')], max_length=10, verbose_name='Status')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Login',
                'verbose_name_plural': 'Logs de Login',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'created_at'], name='core_loginl_usernam_c8a249_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_loginl_ip_addr_a17786_idx'), models.Index(fields=['status', 'created_at'], name='core_loginl_status_761ba9_idx')],
            },
        ),
    ]
