# Generated by Django 5.2.7 on 2026-01-21 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_alter_chat_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("system", "Sistema"),
                    ("user", "Candidato"),
                    ("assistant", "Ada"),
                ],
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="InterviewResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_summary",
                    models.TextField(
                        help_text="Resumo do perfil do aluno baseado nas respostas da entrevista",
                        verbose_name="Resumo do Perfil",
                    ),
                ),
                (
                    "course_recommendations",
                    models.JSONField(
                        help_text="Lista de cursos recomendados com base no perfil",
                        verbose_name="Recomendações de Cursos",
                    ),
                ),
                (
                    "recommendation_justification",
                    models.TextField(
                        help_text="Justificativa para as recomendações de cursos",
                        verbose_name="Justificativa",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Finalizado em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="interviews.chat",
                        verbose_name="Entrevista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado da Entrevista",
                "verbose_name_plural": "Resultados das Entrevistas",
            },
        ),
    ]
